kind: Deployment
apiVersion: apps/v1
metadata:
  name: rutta

spec:
  replicas: 1

  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: "9114"

    spec:
      serviceAccountName: rutta

      containers:
      # For example:
      # docker run --rm -p 3000:3000 -it logary/rutta:latest router --listener http '0.0.0.0:3000' json --target console://
      - name: rutta
        image: logary/rutta
        args: [ "router",
                "--health", "0.0.0.0:9114",
                "--listener", "http", "0.0.0.0:3000", "json",
                "--listener", "udp", "0.0.0.0:14001", "json",
                "--target", "console://." ]

        ports:
        - name: http-json
          containerPort: 3000

        - name: udp-json
          containerPort: 14001

        # The kubelet uses readiness probes to know when a container is ready to start accepting traffic.
        readinessProbe:
          initialDelaySeconds: 0
          httpGet:
            path: /health
            port: 9114

        # Many applications running for long periods of time eventually transition to broken states, and cannot recover except by being restarted. Kubernetes provides liveness probes to detect and remedy such situations.
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 9114

        resources:
          limits:
            cpu: 2500m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 150Mi